import { X } from 'lucide-react';

interface AgentResultWidgetProps {
  title: string;
  columns: string[];
  data: any[];
  onDismiss: () => void;
}

export function AgentResultWidget({ title, columns, data, onDismiss }: AgentResultWidgetProps) {
  return (
    <div className="flex flex-col h-full bg-white relative">
      <div className="p-6 border-b border-[rgba(0,0,0,0.08)] flex justify-between items-center bg-[#FAFAFA]">
        <div>
          <h2 className="text-xl font-semibold text-black tracking-tight">{title}</h2>
          <p className="text-sm text-[#575757] mt-1 tracking-tight">Temporary view generated by Neo</p>
        </div>
        <button
          onClick={onDismiss}
          className="px-4 py-2 border border-[rgba(0,0,0,0.08)] rounded-md text-sm font-medium text-black hover:bg-slate-50 transition-colors flex items-center gap-2"
        >
          <X className="w-4 h-4" />
          Close View
        </button>
      </div>

      <div className="flex-1 p-6 overflow-y-auto">
        <div className="border border-[rgba(0,0,0,0.08)] rounded-lg overflow-hidden bg-white shadow-sm">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-[rgba(0,0,0,0.08)] bg-[#FAFAFA]">
                {columns.map((col, idx) => (
                  <th key={idx} className="px-4 py-3 text-xs font-semibold text-black uppercase tracking-wider">
                    {col}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-[rgba(0,0,0,0.08)]">
              {data.map((row, rowIdx) => (
                <tr key={rowIdx} className="hover:bg-slate-50 transition-colors">
                  {columns.map((col, colIdx) => {
                    const value = row[col] || row[col.toLowerCase()] || row[col.replace(/\s+/g, '')];
                    return (
                      <td key={colIdx} className="px-4 py-3 text-sm text-[#575757] tracking-tight">
                        {typeof value === 'object' ? JSON.stringify(value) : value?.toString() || '-'}
                      </td>
                    );
                  })}
                </tr>
              ))}
              {data.length === 0 && (
                <tr>
                  <td colSpan={columns.length} className="px-4 py-8 text-center text-sm text-[#A3A3A3]">
                    No data found
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
